rules:
  - name: alphacoders
    fileName: alphacoders.yaml
    favicon: favicon_alphacoders.png
    canSearch: true
    
  - name: alphacoders_avatars
    fileName: alphacoders_avatars.yaml 
    favicon: favicon_alphacoders_avatars.png 
    canSearch: false
    
  - name: alphacoders_gif 
    fileName: alphacoders_gif.yaml 
    favicon: favicon_alphacoders_gif.png 
    canSearch: true
    
  - name: alphacoders_mobile 
    fileName: alphacoders_mobile.yaml 
    favicon: favicon_alphacoders_mobile.png 
    canSearch: false
    
  - name: anime_pictures
    fileName: anime_pictures.yaml 
    favicon: favicon_anime_pictures.png 
    canSearch: true

  - name: behoimi 
    fileName: behoimi.yaml 
    favicon: favicon_behoimi.ico 
    canSearch: true

  - name: danbooru 
    fileName: danbooru.yaml 
    favicon: favicon_danbooru.png 
    canSearch: true

  - name: danbooru_pool 
    fileName: danbooru_pool.yaml 
    favicon: favicon_danbooru_pool.png 
    canSearch: false

  - name: gelbooru 
    fileName: gelbooru.yaml 
    favicon: favicon_gelbooru.png 
    canSearch: true

  - name: konachan 
    fileName: konachan.yaml 
    favicon: favicon_konachan.ico 
    canSearch: true

  - name: konachan_pool 
    fileName: konachan_pool.yaml 
    favicon: favicon_konachan_pool.ico 
    canSearch: true

  - name: konchan_chs 
    fileName: konchan_chs.yaml 
    favicon: favicon_konchan_chs.png 
    canSearch: true

  - name: minitokyo_mobile 
    fileName: minitokyo_mobile.yaml 
    favicon: favicon_minitokyo_mobile.jpg 
    canSearch: true

  - name: minitokyo_scans 
    fileName: minitokyo_scans.yaml 
    favicon: favicon_minitokyo_scans.jpg 
    canSearch: true

  - name: minitokyo_wallpaper 
    fileName: minitokyo_wallpaper.yaml 
    favicon: favicon_minitokyo_wallpaper.jpg 
    canSearch: true

  - name: pfp_town 
    fileName: pfp_town.yaml 
    favicon: favicon_pfp_town.ico 
    canSearch: true

  - name: pixiv
    fileName: pixiv.yaml 
    favicon: favicon_pixiv.ico 
    canSearch: true

  - name: safebooru 
    fileName: safebooru.yaml 
    favicon: favicon_safebooru.ico 
    canSearch: true

  - name: shuushuu 
    fileName: shuushuu.yaml 
    favicon: favicon_shuushuu.ico 
    canSearch: true

  - name: wallpaperscraft 
    fileName: wallpaperscraft.yaml 
    favicon: favicon_wallpaperscraft.ico 
    canSearch: true

  - name: yande 
    fileName: yande.yaml 
    favicon: favicon_yande.ico 
    canSearch: true

  - name: yande_pool 
    fileName: yande_pool.yaml 
    favicon: favicon_yande_pool.ico 
    canSearch: true

  - name: zerochan 
    fileName: zerochan.yaml 
    favicon: favicon_zerochan.ico 
    canSearch: true